[package]
name = "tensor"
version = "0.1.0"
edition = "2024"

[dependencies]
kalosm = { version = "0.4.0", features = ["language", "metal"] }
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
bytes = "1.5"
tokio-stream = "0.1"
serde = "1.0.219"