import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "~/app/globals.scss";
import "~/ui/components/base.scss";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" className="tensorui dark">
            <body className={[geist.className, geistMono.className].join(" ")}>{children}</body>
        </html>
    );
}
