import { type Metadata } from "next";
import { Geist } from "next/font/google";

import "~/app/globals.scss";
import "~/ui/components/base.scss";
import { Providers } from "./providers";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <Providers>
            <html lang="en" className="tensorui dark">
                <body className={geist.className}>{children}</body>
            </html>
        </Providers>
    );
}
